Fixed issue with logger being called on validate
This is the error I fixed:
```
debug: trailpack: validating footprints
TypeError: Cannot read property 'warn' of undefined
    at FootprintsTrailpack.validate (/Users/Matteo/Developer/projects/Yeeti/Hamsa/hamsa-api-server/node_modules/trailpack-footprints/index.js:23:19)
    at app.after.then.then (/Users/Matteo/Developer/projects/Yeeti/Hamsa/hamsa-api-server/node_modules/trails/lib/Core.js:188:24)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
    at Function.Module.runMain (module.js:703:11)
    at startup (bootstrap_node.js:190:16)
    at bootstrap_node.js:662:3
(node:30120) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'warn' of undefined
    at FootprintsTrailpack.validate (/Users/Matteo/Developer/projects/Yeeti/Hamsa/hamsa-api-server/node_modules/trailpack-footprints/index.js:23:19)
    at app.after.then.then (/Users/Matteo/Developer/projects/Yeeti/Hamsa/hamsa-api-server/node_modules/trails/lib/Core.js:188:24)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
    at Function.Module.runMain (module.js:703:11)
    at startup (bootstrap_node.js:190:16)
    at bootstrap_node.js:662:3
```